version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 962804699607.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t todo-repo-g3 .
      - docker tag todo-repo-g3:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/todo-repo-g3:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/todo-repo-g3:latest
      - echo writing image definitions file. . .
      - printf '[{"name":"todo-g3container", "imageUri": "962804699607.dkr.ecr.us-west-2.amazonaws.com/todo-repo-g3:latest"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
